version: '3.8'

services:
  zerotier:
    image: zerotier/zerotier:latest
    container_name: zerotier
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - zerotier-one-data:/var/lib/zerotier-one
      - ./zerotier-entrypoint.sh:/zerotier-entrypoint.sh:ro
    environment:
      - ZEROTIER_NETWORK_ID=e3918db4837300f1
    entrypoint: ["/zerotier-entrypoint.sh"]

volumes:
  zerotier-one-data: 