version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: pfcam
      POSTGRES_USER: pfcam
      POSTGRES_PASSWORD: pfcam
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pfcam -d pfcam"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://pfcam:pfcam@postgres:5432/pfcam
      - SECRET_KEY=your-secret-key-here-change-in-production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - STORAGE_PATH=/app/storage
      - FTP_PUBLIC_HOST=192.168.86.25
    volumes:
      - ./backend:/app
      - storage_data:/app/storage
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        python manage_db.py migrate &&
        python init_db.py &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_WS_URL=ws://backend:8000/ws
    depends_on:
      - backend
    restart: unless-stopped

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    restart: unless-stopped
    ports:
      - "8554:8554"   # RTSP
      - "8888:8888"   # HLS
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
    network_mode: bridge

  ftp:
    image: stilliard/pure-ftpd:latest
    container_name: pfcam-ftp-1
    ports:
      - "21:21"
      - "30000-30009:30000-30009"  # Passive port range
    environment:
      - PUBLICHOST=localhost
      - FTP_USER_NAME=ftpuser
      - FTP_USER_PASS=ftppass
      - FTP_USER_HOME=/home/ftpuser/ftp
      - ADDED_FLAGS=--passiveportrange 30000:30009
    volumes:
      - ./ftpdata:/home/ftpuser/ftp
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  storage_data: 