"""Add tags and event_tags tables

Revision ID: 172a271b53ab
Revises: 7823a242aecc
Create Date: 2025-07-19 08:46:10.344984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '172a271b53ab'
down_revision = '7823a242aecc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'is_played',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'is_played',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ### 