"""Add unique constraint on event filename

Revision ID: 249511589253
Revises: 004
Create Date: 2025-07-19 07:36:04.137277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '249511589253'
down_revision = '004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_application_settings_id'), 'application_settings', ['id'], unique=False)
    
    # Add unique constraint on event filename to prevent duplicates
    op.create_unique_constraint('uq_events_filename', 'events', ['filename'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_settings_id'), table_name='application_settings')
    
    # Remove unique constraint on event filename
    op.drop_constraint('uq_events_filename', 'events', type_='unique')
    # ### end Alembic commands ### 