"""Remove unique constraint on filename since we handle deduplication in application logic

Revision ID: 471afe67dd23
Revises: 249511589253
Create Date: 2025-07-19 07:41:17.987711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '471afe67dd23'
down_revision = '249511589253'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_events_filename', 'events', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_events_filename', 'events', ['filename'])
    # ### end Alembic commands ### 