"""Add is_played field to events table

Revision ID: 7823a242aecc
Revises: 8b94489bef6b
Create Date: 2025-07-19 08:13:48.703798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7823a242aecc'
down_revision = '8b94489bef6b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('is_played', sa.Boolean(), nullable=True))
    op.alter_column('events', 'is_orphaned',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'is_orphaned',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('events', 'is_played')
    # ### end Alembic commands ### 