"""Add is_orphaned field to events table

Revision ID: 8b94489bef6b
Revises: 471afe67dd23
Create Date: 2025-07-19 07:54:33.319970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b94489bef6b'
down_revision = '471afe67dd23'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('is_orphaned', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'is_orphaned')
    # ### end Alembic commands ### 