"""remove_optional_storage_settings_add_data_retention_toggle

Revision ID: a0a3380ae8be
Revises: c387a98496b1
Create Date: 2025-07-19 16:05:56.999211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0a3380ae8be'
down_revision = 'c387a98496b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('application_settings', sa.Column('data_retention_enabled', sa.Boolean(), nullable=True))
    
    # Set default value for existing rows
    op.execute("UPDATE application_settings SET data_retention_enabled = true WHERE data_retention_enabled IS NULL")
    
    # Make column not nullable
    op.alter_column('application_settings', 'data_retention_enabled', nullable=False)
    
    # Remove old columns
    op.drop_column('application_settings', 'auto_download_events')
    op.drop_column('application_settings', 'store_data_on_camera')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_settings', sa.Column('store_data_on_camera', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('application_settings', sa.Column('auto_download_events', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('application_settings', 'data_retention_enabled')
    # ### end Alembic commands ### 