"""add_tags_and_event_tags_tables

Revision ID: c387a98496b1
Revises: 172a271b53ab
Create Date: 2025-07-19 09:19:33.861513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c387a98496b1'
down_revision = '172a271b53ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 